import type { SimModule, SymmetryType } from "@/scenes/engine/types";
import { MagneticScene, MAGNETIC_LEVA_SCHEMA } from "./Scene";
import type { MagneticConfig } from "./Scene";
import { MAGNETIC_PRESETS } from "./presets";

const MagneticModule: SimModule<MagneticConfig> = {
  id: "magnetic",
  title: "Magnetic Field",
  description:
    "Charged test particles integrating under the Lorentz force F = qv×B in a field generated by a D_n-symmetric arrangement of magnetic dipoles. Velocity-Verlet integrator (symplectic). Initial conditions on a dihedral ring; particle count and dipole order tunable.",

  defaults: {
    particleCount: 500,
    charge: 1,
    mass: 1,
    B0: 1,
    dt: 0.005,
    trailLength: 200,
    symmetryType: "C",
    symmetryOrder: 1,
  },

  presets: MAGNETIC_PRESETS,

  schema: MAGNETIC_LEVA_SCHEMA,

  Scene: MagneticScene,

  /**
   * Magnetic sim supports both C_n (ring) and D_n (dihedral ring) symmetry
   * for source placement and initial conditions.
   */
  symmetryApplies(type: SymmetryType, order: number): boolean {
    return (type === "C" || type === "D") && order >= 1;
  },
};

export default MagneticModule;
