import type { SimModule, PerfTier, SymmetryType } from '@/scenes/engine/types'
import { MagneticScene, MAGNETIC_LEVA_SCHEMA } from './Scene'
import type { MagneticConfig } from './Scene'
import { MAGNETIC_PRESETS } from './presets'

// CPU-only sim: scene manages its own particle array via useRef
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface MagneticState {}

const MagneticModule: SimModule<MagneticConfig, MagneticState> = {
  id: 'magnetic',
  title: 'Magnetic Field',
  description:
    'Charged test particles integrating under the Lorentz force F = qv×B in a field generated by a D_n-symmetric arrangement of magnetic dipoles. Velocity-Verlet integrator (symplectic). Initial conditions on a dihedral ring; particle count and dipole order tunable.',

  defaults: {
    particleCount: 500,
    charge: 1,
    mass: 1,
    B0: 1,
    dt: 0.005,
    trailLength: 200,
    symmetryType: 'C',
    symmetryOrder: 1,
  },

  presets: MAGNETIC_PRESETS,

  schema: MAGNETIC_LEVA_SCHEMA,

  Scene: MagneticScene,

  init(_config: MagneticConfig, _perf: PerfTier): MagneticState {
    // Integration happens inside Scene.tsx via useFrame; no CPU state here
    return {}
  },

  step(_state: MagneticState, _dt: number): void {
    // No integration step at module level; all animation is driven by useFrame
  },

  dispose(_state: MagneticState): void {
    // No GPU resources to release
  },

  /**
   * Magnetic sim supports both C_n (ring) and D_n (dihedral ring) symmetry
   * for source placement and initial conditions.
   */
  symmetryApplies(type: SymmetryType, order: number): boolean {
    return (type === 'C' || type === 'D') && order >= 1
  },
}

export default MagneticModule
